/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: ../studio/schema.json
export type Publication = {
  _id: string;
  _type: "publication";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  year?: number;
  category?:
    | "articulo-wos"
    | "actas-capitulos"
    | "articulo-indexado"
    | "revista-nacional"
    | "otras"
    | "libro";
  citation?: string;
  collaborators?: string;
  link?: string;
  featured?: boolean;
  legacyId?: string;
};

export type Link = {
  _type: "link";
  label?: string;
  url?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Seo = {
  _type: "seo";
  metaTitle?: string;
  metaDescription?: string;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type TranslationMetadata = {
  _id: string;
  _type: "translation.metadata";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  translations?: InternationalizedArrayReference;
  schemaTypes?: Array<string>;
};

export type InternationalizedArrayReference = Array<
  {
    _key: string;
  } & InternationalizedArrayReferenceValue
>;

export type HomePageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "homePage";
};

export type BiografiaPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "biografiaPage";
};

export type InvestigacionPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "investigacionPage";
};

export type DocenciaPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "docenciaPage";
};

export type PublicacionesPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "publicacionesPage";
};

export type ContactoPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "contactoPage";
};

export type SiteSettingsReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "siteSettings";
};

export type InternationalizedArrayReferenceValue = {
  _type: "internationalizedArrayReferenceValue";
  value?:
    | HomePageReference
    | BiografiaPageReference
    | InvestigacionPageReference
    | DocenciaPageReference
    | PublicacionesPageReference
    | ContactoPageReference
    | SiteSettingsReference;
  language?: string;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  footerLinks?: Array<
    {
      _key: string;
    } & Link
  >;
  footerInfo?: Array<
    {
      _key: string;
    } & Link
  >;
  cv?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  sameAs?: Array<string>;
  defaultSeo?: Seo;
};

export type ContactoPage = {
  _id: string;
  _type: "contactoPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  heading?: string;
  intro?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  email?: string;
  address?: string;
  seo?: Seo;
};

export type PublicacionesPage = {
  _id: string;
  _type: "publicacionesPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  heading?: string;
  intro?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  seo?: Seo;
};

export type DocenciaPage = {
  _id: string;
  _type: "docenciaPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  heading?: string;
  eyebrow?: string;
  intro?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  doctorates?: Array<{
    name?: string;
    year?: string;
    position?: string;
    country?: string;
    _key: string;
  }>;
  postdocs?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  programs?: Array<{
    name?: string;
    period?: string;
    description?: string;
    _key: string;
  }>;
  seo?: Seo;
};

export type PublicationReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "publication";
};

export type InvestigacionPage = {
  _id: string;
  _type: "investigacionPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  heading?: string;
  intro?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  areas?: Array<{
    title?: string;
    slug?: Slug;
    summary?: string;
    body?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    applications?: Array<string>;
    keyPublications?: Array<
      {
        _key: string;
      } & PublicationReference
    >;
    _type: "researchArea";
    _key: string;
  }>;
  seo?: Seo;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type BiografiaPage = {
  _id: string;
  _type: "biografiaPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  heading?: string;
  intro?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  awards?: Array<{
    name?: string;
    description?: string;
    year?: string;
    _key: string;
  }>;
  seo?: Seo;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  displayName?: string;
  affiliation?: string;
  portrait?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  stats?: Array<{
    value?: string;
    label?: string;
    _key: string;
  }>;
  timeline?: Array<{
    decade?: string;
    caption?: string;
    body?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    _key: string;
  }>;
  seo?: Seo;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Publication
  | Link
  | SanityImageAssetReference
  | Seo
  | TranslationMetadata
  | InternationalizedArrayReference
  | HomePageReference
  | BiografiaPageReference
  | InvestigacionPageReference
  | DocenciaPageReference
  | PublicacionesPageReference
  | ContactoPageReference
  | SiteSettingsReference
  | InternationalizedArrayReferenceValue
  | SanityFileAssetReference
  | SiteSettings
  | ContactoPage
  | PublicacionesPage
  | DocenciaPage
  | PublicationReference
  | InvestigacionPage
  | Slug
  | BiografiaPage
  | HomePage
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: lib/sanity/queries.ts
// Variable: PUBLICATIONS_QUERY
// Query: *[_type == "publication"] | order(year desc, title asc) {    _id, title, citation, year, category, collaborators, link, featured  }
export type PUBLICATIONS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  citation: string | null;
  year: number | null;
  category:
    | "actas-capitulos"
    | "articulo-indexado"
    | "articulo-wos"
    | "libro"
    | "otras"
    | "revista-nacional"
    | null;
  collaborators: string | null;
  link: string | null;
  featured: boolean | null;
}>;

// Source: lib/sanity/queries.ts
// Variable: HOME_PAGE_QUERY
// Query: *[_id == $id && _type == "homePage"][0]
export type HOME_PAGE_QUERY_RESULT = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  displayName?: string;
  affiliation?: string;
  portrait?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  stats?: Array<{
    value?: string;
    label?: string;
    _key: string;
  }>;
  timeline?: Array<{
    decade?: string;
    caption?: string;
    body?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    _key: string;
  }>;
  seo?: Seo;
} | null;

// Source: lib/sanity/queries.ts
// Variable: BIOGRAFIA_PAGE_QUERY
// Query: *[_id == $id && _type == "biografiaPage"][0]
export type BIOGRAFIA_PAGE_QUERY_RESULT = {
  _id: string;
  _type: "biografiaPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  heading?: string;
  intro?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  awards?: Array<{
    name?: string;
    description?: string;
    year?: string;
    _key: string;
  }>;
  seo?: Seo;
} | null;

// Source: lib/sanity/queries.ts
// Variable: INVESTIGACION_PAGE_QUERY
// Query: *[_id == $id && _type == "investigacionPage"][0]
export type INVESTIGACION_PAGE_QUERY_RESULT = {
  _id: string;
  _type: "investigacionPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  heading?: string;
  intro?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  areas?: Array<{
    title?: string;
    slug?: Slug;
    summary?: string;
    body?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    applications?: Array<string>;
    keyPublications?: Array<
      {
        _key: string;
      } & PublicationReference
    >;
    _type: "researchArea";
    _key: string;
  }>;
  seo?: Seo;
} | null;

// Source: lib/sanity/queries.ts
// Variable: DOCENCIA_PAGE_QUERY
// Query: *[_id == $id && _type == "docenciaPage"][0]
export type DOCENCIA_PAGE_QUERY_RESULT = {
  _id: string;
  _type: "docenciaPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  heading?: string;
  eyebrow?: string;
  intro?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  doctorates?: Array<{
    name?: string;
    year?: string;
    position?: string;
    country?: string;
    _key: string;
  }>;
  postdocs?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  programs?: Array<{
    name?: string;
    period?: string;
    description?: string;
    _key: string;
  }>;
  seo?: Seo;
} | null;

// Source: lib/sanity/queries.ts
// Variable: PUBLICACIONES_PAGE_QUERY
// Query: *[_id == $id && _type == "publicacionesPage"][0]
export type PUBLICACIONES_PAGE_QUERY_RESULT = {
  _id: string;
  _type: "publicacionesPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  heading?: string;
  intro?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  seo?: Seo;
} | null;

// Source: lib/sanity/queries.ts
// Variable: CONTACTO_PAGE_QUERY
// Query: *[_id == $id && _type == "contactoPage"][0]
export type CONTACTO_PAGE_QUERY_RESULT = {
  _id: string;
  _type: "contactoPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  heading?: string;
  intro?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  email?: string;
  address?: string;
  seo?: Seo;
} | null;

// Source: lib/sanity/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_id == $id && _type == "siteSettings"][0]
export type SITE_SETTINGS_QUERY_RESULT = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  footerLinks?: Array<
    {
      _key: string;
    } & Link
  >;
  footerInfo?: Array<
    {
      _key: string;
    } & Link
  >;
  cv?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  sameAs?: Array<string>;
  defaultSeo?: Seo;
} | null;

// Query TypeMap
declare global {
  interface SanityQueries {
    '\n  *[_type == "publication"] | order(year desc, title asc) {\n    _id, title, citation, year, category, collaborators, link, featured\n  }\n': PUBLICATIONS_QUERY_RESULT;
    '*[_id == $id && _type == "homePage"][0]': HOME_PAGE_QUERY_RESULT;
    '*[_id == $id && _type == "biografiaPage"][0]': BIOGRAFIA_PAGE_QUERY_RESULT;
    '*[_id == $id && _type == "investigacionPage"][0]': INVESTIGACION_PAGE_QUERY_RESULT;
    '*[_id == $id && _type == "docenciaPage"][0]': DOCENCIA_PAGE_QUERY_RESULT;
    '*[_id == $id && _type == "publicacionesPage"][0]': PUBLICACIONES_PAGE_QUERY_RESULT;
    '*[_id == $id && _type == "contactoPage"][0]': CONTACTO_PAGE_QUERY_RESULT;
    '*[_id == $id && _type == "siteSettings"][0]': SITE_SETTINGS_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
